### ISSUE TITLE
[Task] Unified Home/All/Search Page

### ISSUE THREAD

**Issue by hay-kot** [mealie-recipes/mealie#2148]
Subtasks: 

- [x] Fix mobile view for search page - #2150 
- [x] Use debounce filter and remove search button - #2150
- [x] Don't autofocus text field - #2150
- [ ] Make "search" the new main page.
  - [x] Replace `/` with search page - #2150 
  - [ ] Remove all recipes page (requires infinite scroll)
- [ ] Remove of max results and use infinite scrolling as on other pages
- [ ] Remove Routing for Pages
  - [x] `/search` is now `/` - #2150
  - [ ] `/recipes/all` is now `/` 

---

### Discussed in https://github.com/hay-kot/mealie/discussions/2133

<div type='discussions-op-text'>

<sup>Originally posted by **fleshgolem** February 14, 2023</sup>
Hay-Kot talked about this when doing the new search page and ever since i cant help but be somewhat annoyed that these 3 different pages that all basically do the same thing even exist
So here is my proposal on how to do this in a way that shouldn't really reduce any current functionality:

* Make "search" the new main page. Get rid of recent and all recipes
* Store last used sort order in localstorage. Maybe display a bit more prominently on mobile
* Get rid of max result setting and just use infinite scrolling as in other places
* Get rid of big search button and just do a debounced fire on all parameter changes
* Dont autofocus text-field

I think, i should be able to make most of those changes myself, but its really not something i want to get started on before putting the idea up to check if i am missing things or there are potential problems. Thoughts?

</div>

**Comment by fleshgolem** [comment]
Debounced search works pretty well from some preliminary testing, but i could find one issue:
If you enter a search term and then hit the clear button on the text field, the recipe list will stay empty until you enter a new term. Manually deleting the letters works fine, just the clear button does not

**Comment by hay-kot** [comment]
> Debounced search works pretty well from some preliminary testing, but i could find one issue:
> If you enter a search term and then hit the clear button on the text field, the recipe list will stay empty until you enter a new term. Manually deleting the letters works fine, just the clear button does not

I saw this too after the fact. Guessing it sets it to undefined/null instead of any empty string, but I haven't look at it.
