### ISSUE TITLE
RC-1 Checklist/Chores

### ISSUE THREAD

**Issue by hay-kot** [mealie-recipes/mealie#2478]
- [x] New Scraper Issue Template with more detailed questions  - https://github.com/hay-kot/mealie/pull/2481
- [x] Refine Issue template - https://github.com/hay-kot/mealie/pull/2481
  - [x] Require Logs?
  - [x] Require Reproduction Steps
  - [x] Can it be replicated on the demo site?
  - [x] Others...
- [x] Refine Feature Request links https://github.com/hay-kot/mealie/pull/2481
- [x] Move to GH organization
- [x] Invite contributors. 
- [x] Write up how-to-release release documentation
- [x] Kill old docs site and replace with v1 docs - GH Docs now redirect to docs.mealie.io
- [x] Draft Basic/Vague Change log
- [x] #2539 
- [x] #2195

**Comment by michael-genson** [comment]
We might want to fix https://github.com/mealie-recipes/mealie/issues/2577 before release, too
