### ISSUE TITLE
[BUG] - Setting theme primary colour doesn't change theme-color meta

### ISSUE THREAD

**Issue by tecosaur** [mealie-recipes/mealie#4563]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I've recently customised the `THEME_DARK_ACCENT` and `THEME_LIGHT_PRIMARY` on my Mealie instance. After figuring out the caching issues, I've noticed that the `theme-color` meta tag isn't affected by this, leading to what I'd consider a UI bug:

![ima_83684e1](https://github.com/user-attachments/assets/0e8a2df8-2dab-46fb-970a-ec3bd4edb957)

On iOS for instance, the orange banner appears as you start scrolling, which is rather jarring difference from the selected primary colour used in the banner.

### Steps to Reproduce

- Customise your mealie colours
- Observe

### Please provide relevant logs

n/a

### Mealie Version

v2.2.0

### Deployment

Other (please specify below)

### Additional Deployment Details

On NixOS

**Comment by Kuchenpirat** [comment]
The theme color meta tag is set to primary there here: https://github.com/mealie-recipes/mealie/blob/aceed2a11e35749575115a9b3739bad9f51ef204/frontend/nuxt.config.js#L363

But i could reproduce it not having any effect so marking as confirmed 👍

**Comment by bloominstrong** [comment]
Having a look at the code the problem is that the pwa theme_color does is set at build time and needs to be set at runtime.
I will have a try at changing it to a runtimeConfig.

**Comment by bloominstrong** [comment]
So it seems like the pwa module [does not support runtimeConfig's](https://github.com/nuxt-community/pwa-module/issues/477). I don't have the skill or knowledge to attempt to fix that but I have got workarounds for docker and NixOS users.

## Docker workaround
You need to manually change the color and build the container yourself.
```
git clone https://github.com/mealie-recipes/mealie.git
cd mealie
git checkout $PREFERRED_VERSION
cp docker/Dockerfile .
sed -i -E "s//E58325/$YOUR_COLOR/" ./frontend/nuxt.config.js
docker build -t my-mealie --platform linux/amd64 .
docker run my-mealie
```

## NixOS workaround
I tried to do this in an override but I couldn't get there and ended up using a local copy of nixpkgs which is not ideal as you will need to `git rebase` to update the system
```
git clone --branch nixos-24.11 --depth=1 https://github.com/NixOS/nixpkgs.git
cd nixpkgs
$EDITOR pkgs/by-name/me/mealie/mealie-frontend.nix 
```
in here you want to add in the below 
```
postPatch = ''
sed -i -E "s/E58325/$YOUR_COLOR/" nuxt.config.js
'';
```
then commit it and rebuild
```
git add pkgs/by-name/me/mealie/mealie-frontend.nix 
git commit
nixos-rebuild -I nixpkgs=/path/to/nixpkgs switch 
```

**Comment by matthewkdies** [comment]
> You need to manually change the color and build the container yourself.
> ```
> git clone https://github.com/mealie-recipes/mealie.git
> cd mealie
> git checkout $PREFERRED_VERSION
> cp docker/Dockerfile .
> sed -i -E "s//E58325/$YOUR_COLOR/" ./frontend/nuxt.config.js
> docker build -t my-mealie --platform linux/amd64 .
> docker run my-mealie
> ```

Can confirm that this works! After completely closing the PWA and restarting, my issue is resolved.

<img src="https://github.com/user-attachments/assets/5df55783-8842-48b6-8701-62cb358ff448" alt="Alt Text" height="500">

**Comment by Mraedis** [comment]
@tecosaur does it work if you specify the colour without the # ?

**Comment by michael-genson** [comment]
If removing the `#` works we can easily chop that off in-app

**Comment by matthewkdies** [comment]
I just checked with the latest image and my locally built image, and this still occurs if the `#` is omitted from the color-controlling variables. Based on @bloominstrong's earlier comment, it seems that this is because it's a build-time variable:

> Having a look at the code the problem is that the pwa theme_color does is set at build time and needs to be set at runtime.

**Comment by seva-luchianov** [comment]
Just hit this today after first time setup
